version: '3.8'

services:

  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn webapp.wsgi:application --bind 0.0.0.0:8002
    ports:
      - 8002:8002
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  postgres_data: